/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ApiSocControlRouteImport } from './routes/api/soc.control'
import { Route as ApiSocRunRouteImport } from './routes/api/soc.run'
import { Route as ApiSocStateRouteImport } from './routes/api/soc.state'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocControlRoute = ApiSocControlRouteImport.update({
  id: '/api/soc/control',
  path: '/api/soc/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocRunRoute = ApiSocRunRouteImport.update({
  id: '/api/soc/run',
  path: '/api/soc/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocStateRoute = ApiSocStateRouteImport.update({
  id: '/api/soc/state',
  path: '/api/soc/state',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/queue': typeof QueueRoute
  '/api/soc/control': typeof ApiSocControlRoute
  '/api/soc/run': typeof ApiSocRunRoute
  '/api/soc/state': typeof ApiSocStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/queue': typeof QueueRoute
  '/api/soc/control': typeof ApiSocControlRoute
  '/api/soc/run': typeof ApiSocRunRoute
  '/api/soc/state': typeof ApiSocStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/queue': typeof QueueRoute
  '/api/soc/control': typeof ApiSocControlRoute
  '/api/soc/run': typeof ApiSocRunRoute
  '/api/soc/state': typeof ApiSocStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit'
    | '/queue'
    | '/api/soc/control'
    | '/api/soc/run'
    | '/api/soc/state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/queue'
    | '/api/soc/control'
    | '/api/soc/run'
    | '/api/soc/state'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audit'
    | '/queue'
    | '/api/soc/control'
    | '/api/soc/run'
    | '/api/soc/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRoute
  QueueRoute: typeof QueueRoute
  ApiSocControlRoute: typeof ApiSocControlRoute
  ApiSocRunRoute: typeof ApiSocRunRoute
  ApiSocStateRoute: typeof ApiSocStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soc/control': {
      id: '/api/soc/control'
      path: '/api/soc/control'
      fullPath: '/api/soc/control'
      preLoaderRoute: typeof ApiSocControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soc/run': {
      id: '/api/soc/run'
      path: '/api/soc/run'
      fullPath: '/api/soc/run'
      preLoaderRoute: typeof ApiSocRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soc/state': {
      id: '/api/soc/state'
      path: '/api/soc/state'
      fullPath: '/api/soc/state'
      preLoaderRoute: typeof ApiSocStateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRoute,
  QueueRoute: QueueRoute,
  ApiSocControlRoute: ApiSocControlRoute,
  ApiSocRunRoute: ApiSocRunRoute,
  ApiSocStateRoute: ApiSocStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
